name: CMake

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '.github/workflows/*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        BUILD_TYPE: [Release, Debug]

    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build --config Debug
